### ISSUE TITLE
Mismatched types error when compiling libz-rs-sys with gzprintf feature

### ISSUE THREAD

**Issue by musicinmybrain** [trifectatechfoundation/zlib-rs#469]
Working on Fedora 43, with `rustc 1.92.0 (ded5c06cf 2025-12-08) (Fedora 1.92.0-1.fc43)`:

```
$ git clone https://github.com/trifectatechfoundation/zlib-rs.git
$ cd zlib-rs/libz-rs-sys
$ cargo test -F gzprintf
[…]
error[E0308]: mismatched types
    --> libz-rs-sys/src/gz.rs:2702:38
     |
2702 |     unsafe { gzvprintf(file, format, va) }
     |              ---------               ^^ expected `VaList<'_, '_>`, found `VaListImpl<'_>`
     |              |
     |              arguments to this function are incorrect
     |
note: function defined here
    --> libz-rs-sys/src/gz.rs:2723:26
     |
2723 | pub unsafe extern "C" fn gzvprintf(
     |                          ^^^^^^^^^
...
2726 |     va: core::ffi::VaList,
     |     ---------------------

Some errors have detailed explanations: E0308, E0554.
For more information about an error, try `rustc --explain E0308`.
```
